version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - my_network

  python_app:
    image: my-app:latest
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_network

networks:
  my_network:
    driver: bridge