apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000  # Replace this with the port your Flask app listens on
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379  # Redis port
  type: LoadBalancer  # Change this based on your networking requirements
